### ISSUE TITLE
Not working with Angular 4.2.6

### ISSUE THREAD

**Issue by tezine** [aspnet/JavaScriptServices#1105]
Hi, 
I'm trying to port a regular Angular project from Angular CLI to Asp.net with SPA Template. 
Whenever I run the application, I get the following warnings: 

```
Now listening on: http://*:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.NodeServices[0]
      webpack built 93fa9b3e4b8d9574ed88 in 24599ms
fail: Microsoft.AspNetCore.NodeServices[0]
      Hash: 93fa9b3e4b8d9574ed88
      Version: webpack 2.5.1
      Time: 24599ms
                                     Asset     Size  Chunks                    Chunk Names
      7c2b8d07671fe017e99941273b137bc4.jpg   285 kB          [emitted]  [big]  
                            main-client.js  7.99 MB       0  [emitted]  [big]  main-client
                        main-client.js.map  8.82 MB       0  [emitted]         main-client
      chunk    {0} main-client.js, main-client.js.map (main-client) 7.38 MB [entry] [rendered]
          [0] delegated ./node_modules/@angular/core/@angular/core.es5.js from dll-reference vendor_b7199ba5a0e681456630 42 bytes {0} [not cacheable] [built]
          [8] external "vendor_b7199ba5a0e681456630" 42 bytes {0} [not cacheable]
        [523] (webpack)/buildin/module.js 517 bytes {0} [built]
        [534] ./ClientApp/boot-client.ts 1.09 kB {0} [built]
        [535] (webpack)-hot-middleware/client.js?path=%2F__webpack_hmr 6.68 kB {0} [built]
        [536] delegated ./node_modules/event-source-polyfill/eventsource.js from dll-reference vendor_b7199ba5a0e681456630 42 bytes {0} [not cacheable] [built]
        [611] ./ClientApp/app/app.module.client.ts 9.9 kB {0} [built]
       [1080] ./~/querystring-es3/index.js 127 bytes {0} [built]
       [1081] ./~/reflect-metadata/Reflect.js 48 kB {0} [built]
       [1317] ./~/strip-ansi/index.js 161 bytes {0} [built]
       [1388] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
       [1389] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
       [1395] delegated ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js from dll-reference vendor_b7199ba5a0e681456630 42 bytes {0} [not cacheable] [built]
       [1396] delegated ./node_modules/zone.js/dist/zone.js from dll-reference vendor_b7199ba5a0e681456630 42 bytes {0} [not cacheable] [built]
       [1413] multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./ClientApp/boot-client.ts 52 bytes {0} [built]
           + 1399 hidden modules
      
      WARNING in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
      47:2-18 "export 'AnimationBuilder' was not found in '@angular/animations'
      
      WARNING in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
      78:2-18 "export 'AnimationFactory' was not found in '@angular/animations'
      
      WARNING in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
      612:15-31 "export 'AnimationBuilder' was not found in '@angular/animations'
      
      WARNING in ./~/@angular/animations/@angular/animations/browser.es5.js
      39:35-45 "export 'ɵPRE_STYLE' was not found in '@angular/animations'
      
      WARNING in ./~/@angular/animations/@angular/animations/browser.es5.js
      2214:29-39 "export 'ɵPRE_STYLE' was not found in '@angular/animations'
      
      WARNING in ./~/@angular/animations/@angular/animations/browser.es5.js
      3802:97-107 "export 'ɵPRE_STYLE' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/toggle/toggle.directive.js
      78:65-74 "export 'animation' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/toggle/toggle.directive.js
      100:65-74 "export 'animation' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/toggle/toggle.directive.js
      158:8-24 "export 'AnimationBuilder' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/fade/fade.directive.js
      86:67-76 "export 'animation' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/fade/fade.directive.js
      105:68-77 "export 'animation' was not found in '@angular/animations'
      
      WARNING in ./~/@covalent/core/common/animations/fade/fade.directive.js
      170:8-24 "export 'AnimationBuilder' was not found in '@angular/animations'
```

If I attempt to open localhost:5000, the following errors are shown: 
```
Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Teste.Controllers.HomeController.Index (TLOGBackend) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\tezine\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Teste.Controllers.HomeController.Index (TLOGBackend) in 3672.5781ms
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (native)
    at __extends (R:\Projetos\Teste\ClientApp\dist\main-server.js:75584:5)
    at R:\Projetos\Teste\ClientApp\dist\main-server.js:75602:5
    at R:\Projetos\Teste\ClientApp\dist\main-server.js:75630:2
    at Object.setPrototypeOf.__proto__ (R:\Projetos\Teste\ClientApp\dist\main-server.js:75558:10)
    at Object.<anonymous> (R:\Projetos\Teste\ClientApp\dist\main-server.js:75561:2)
    at __webpack_require__ (R:\Projetos\Teste\ClientApp\dist\main-server.js:20:30)
    at Object.setPrototypeOf.__proto__ (R:\Projetos\Teste\ClientApp\dist\main-server.js:36114:177)
    at Object.<anonymous> (R:\Projetos\Teste\ClientApp\dist\main-server.js:36117:2)
    at __webpack_require__ (R:\Projetos\Teste\ClientApp\dist\main-server.js:20:30)
Current directory is: R:\Projetos\Teste
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.<ProcessAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 4458.9698ms 500 text/html; charset=utf-8
```

I'm using typescript 2.3.4 under Windows 10 64bits. 
I already tried to remove node_modules folder, and reinstall every package again.  
All my components are set in app.module.shared.ts. 
All my services are set in app.module.client.ts. 
All imported modules are set in app.module.client.ts. 

Follow my package.json below: 
```
{
  "name": "Teste",
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "^4.2.6",
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/material": "2.0.0-beta.7",
    "@angular/platform-browser": "^4.2.6",
    "@angular/platform-browser-dynamic": "^4.2.6",
    "@angular/platform-server": "^4.2.6",
    "@angular/router": "^4.2.6",
    "@angular/upgrade": "^4.2.6",
    "@covalent/core": "^1.0.0-beta.5-1",
    "@covalent/dynamic-forms": "^1.0.0-beta.5-1",
    "@covalent/highlight": "^1.0.0-beta.5-1",
    "@covalent/http": "^1.0.0-beta.5-1",
    "@covalent/markdown": "^1.0.0-beta.5-1",
    "@ngx-translate/core": "^7.0.0",
    "@ngx-translate/http-loader": "^0.1.0",
    "@swimlane/ngx-datatable": "^9.3.1",
    "@types/geojson": "1.0.2",
    "@types/hammerjs": "^2.0.33",
    "@types/leaflet": "^1.0.65",
    "@types/leaflet-draw": "^0.4.6",
    "@types/node": "7.0.18",
    "angular-leaflet-directive": "^0.10.0",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.4.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^2.0.5",
    "aspnet-webpack": "^1.0.29",
    "awesome-typescript-loader": "3.1.3",
    "bootstrap": "^4.0.0-alpha.6",
    "chart.js": "^2.6.0",
    "core-js": "^2.4.1",
    "css": "2.2.1",
    "css-loader": "0.28.1",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.0",
    "file-loader": "0.11.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "karma-jasmine": "^1.1.0",
    "leaflet": "^1.1.0",
    "leaflet-draw": "^0.4.10",
    "mapbox": "^1.0.0-beta7",
    "mapbox.js": "^3.1.1",
    "md2": "^0.0.25",
    "moment": "^2.18.1",
    "ng2-dnd": "^4.2.0",
    "ngx-accordion": "0.0.17",
    "preboot": "4.5.2",
    "primeng": "^4.1.0-rc.3",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.4.2",
    "style-loader": "0.17.0",
    "to-string-loader": "1.1.5",
    "ts-helpers": "^1.1.2",
    "tslint": "^4.3.1",
    "typescript": "2.3.2",
    "typescript-dotnet": "^4.9.6",
    "typescript-dotnet-amd": "^4.9.6",
    "url-loader": "0.5.8",
    "webpack": "2.5.1",
    "webpack-hot-middleware": "2.18.0",
    "webpack-merge": "4.1.0",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@types/chai": "3.5.2",
    "@types/jasmine": "2.5.47",
    "chai": "3.5.0",
    "jasmine-core": "2.6.1",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3"
  }
}
```

Follow my tsconfig.json below:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,//para contornar lass 'Subject<T>' incorrectly extends base class 'Observable<T>'
    "lib": [ "es6", "dom" ],
    "strict":true,
    "noImplicitThis": false,
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "types": [ "node" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false }
}
```
I had to patch the boot-client.ts in order to work with typescript strict: 
```
let brunoWorkaround: any = (<any>module)['hot'];

if (brunoWorkaround /*module['hot']*/) {
    brunoWorkaround.accept();
    brunoWorkaround.dispose(() => {
        // Before restarting the app, we create a new root element and dispose the old one
        const oldRootElem = document.querySelector('app');
        const newRootElem = document.createElement('app');
        if(oldRootElem && oldRootElem.parentNode) oldRootElem.parentNode.insertBefore(newRootElem, oldRootElem);
        modulePromise.then(appModule => appModule.destroy());
    });
} else {
    enableProdMode();
}
```

The same project is working fine when using ng serve instead of asp.net.

**Comment by SteveSandersonMS** [comment]
Are you saying the issue is that when you add `strict:true` to your `tsconfig.json`, then you get a compiler error that you fixed by modifying `boot-client.ts`? If so, that's something we might change in the future, but having `strict` mode on by default hasn't been a design goal so far. In that case, I'll mark this closed as not something we're planning to change in the short term.

If you're saying there is some other bug in the code in this repo, could you please reopen with more specific details of what the bug is. Thanks!

**Comment by rasert** [comment]
I had the same warnings from Webpack after trying to update Angular from 4.1.2 to 4.2.5. The application won't work. I'll try again to get the error messages.

**Comment by tezine** [comment]
This issue shouldn't be closed. It has nothing related to strict mode. It still doesn't work without strict set! 
:-(

**Comment by SteveSandersonMS** [comment]
@tezine Can you describe succinctly what the issue is? If it's a bug, can you give repro steps?

I'm confident that in general it will be fine with Angular 4.2.5 and 4.2.6 because the latest template in the repo is on 4.2.5, and I tested upgrading to 4.2.6 yesterday without problem.
