### ISSUE TITLE
Webpack 4 issue with Visual Studio 2017 .net core 2.0.7

### ISSUE THREAD

**Issue by AlejandroFlorin** [aspnet/JavaScriptServices#1643]
My project is based on the Angular template for VS 2017 .net core 2.0 (not the new 2.1 templates, yet).

I've upgraded my project to webpack 4. I have update the webpack.config files (main and vendor) to handle the changes and have tweaked the csproj file to use the new --mode parameter required by webpack 4. I can build and publish ok and can run both webpack configs (main and vendor) without problems.

However, when I launch the app in dev mode (CTRL-F5) and VS automatically re-runs webpack, I get a console warning that 'mode' option has not been set and it falls back to Production mode.

How to I make VS call the hot middleware webpack rebuild with the new --mode=development parameter?

Is it an option in startup.cs? Maybe an additional option here?

```
app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
                    HotModuleReplacement = true
                });
```

**Comment by AndyCJ** [comment]
Webpack V4 is currently unsupported as far as I'm aware.

[Here's](https://github.com/aspnet/JavaScriptServices/issues/1562) the still open issue about it.

**Comment by AlejandroFlorin** [comment]
OK, then. I'll have to roll back. Thanks.

**Comment by zhaparoff** [comment]
@AlejandroFlorin, 
As far as I know, HMR middleware just calls 'webpack' command, without any parameters.
So to provide a mode option to HMR you need to specify it in your webpack config file:
```javascript
module.exports = (env) => {
    const isDevBuild = !(env && env.prod);
    const mode = isDevBuild ? 'development' : 'production';
    const config = {
        mode: mode
    };
    return [config];
};
```

You could found more details in the official docs: https://webpack.js.org/concepts/mode

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @zhaparoff!

Also note that we just released an updated `aspnet-webpack` 3.0.0 that adds Webpack 4 support.

**Comment by AlejandroFlorin** [comment]
I have upgraded to aspnet-webpack 3.0.0 as well as used @zhaparoff recommended settings. I still get the warning but I assume that is innocuous as setting the mode inside the webpack.config.js directly covers it?

**Comment by AlejandroFlorin** [comment]
This is still no good. The middleware is doing a full webpack rebuild with every TS change.

**Comment by zhaparoff** [comment]
@AlejandroFlorin,
Looking at your current config, mode isn't included in any output.
You should add mode setting into sharedConfig directly:
```javascript
const sharedConfig = {
        mode: mode,
        stats: { modules: false },
        context: __dirname,
        ...
}
```
OR 
merge 'config' whith 'sharedConfig':
```javascript
const sharedConfig = merge(config, {
        stats: { modules: false },
        context: __dirname,
        ...
});
```
