### ISSUE TITLE
IIS Express + SSL certificate for localhost + HMR

### ISSUE THREAD

**Issue by RazvanADumitru** [aspnet/JavaScriptServices#482]
Hi guys,

So i have an ASP.NET Core app that is running on 'https://localhost:44328/home' that is currently specified in launchSettings.json.

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "https://localhost:44328/",
      "sslPort": 44328
    }
    ....
}
```

What i currently have: 
```
           app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true,                
                    ConfigFile = "config/webpack.config.js"
                });
```

My problem: 

Is there a way to specify that you want to get the hmr server to run over https?

![image](https://cloud.githubusercontent.com/assets/4084252/20791630/9d741752-b7c6-11e6-9efd-7e89cc770887.png)

**Comment by RazvanADumitru** [comment]
I was able to find the following comment after some search:
     // Also note that the webpack HMR service always uses HTTP, even if your app server uses HTTPS,
    // because the HMR service has no need for HTTPS (the client doesn't see it directly - all traffic
    // to it is proxied), and the HMR service couldn't use HTTPS anyway (in general it wouldn't have
   // the necessary certificate).

So if this is the wanted behavior, we can close this issue, and it will probably remain here as a reference for further mates that are trying to achieve this.

**Comment by SteveSandersonMS** [comment]
As it happens, this was fixed yesterday :) The latest package (SpaServices 1.1.0-beta-000002) proxies the `/__webpack_hmr` requests through the same connection that your browser is making to your ASP.NET site, so it works just the same whether you're using HTTP or HTTPS.

Note that to update to 1.1.0-beta-000002, you will also need to update to ASP.NET Core 1.1.0.

**Comment by RazvanADumitru** [comment]
I updated to 1.1.0-beta-000002 and ASP.NET Core 1.1.0, but the problem persists.

All the requests are done via HTTPS.

For example (vendor resource):
![image](https://cloud.githubusercontent.com/assets/4084252/20988897/6065d6ce-bcdb-11e6-9b41-67c5cd504348.png)

I don't have any rewrite rule in web.config or anything else.

**Comment by RazvanADumitru** [comment]
Hi Steve, 

I updated the application to ASP.NET Core 1.1.0 and the package to 1.1.0-beta-000002, but the problem still persists.

Example request (for vendor resource):
![image](https://cloud.githubusercontent.com/assets/4084252/20989622/08ce319c-bcde-11e6-9646-79a797987939.png)

The initialization code for webpack dev middleware remained the same: 
```
   app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true,                
                    ConfigFile = "config/webpack.config.js"
                });
```

**Comment by SteveSandersonMS** [comment]
What version of `aspnet-webpack` are you on? You need 1.0.25 or later to get this feature. Sorry I didn't mention that in my previous comment.

**Comment by RazvanADumitru** [comment]
I was on 1.0.24. I updated the package to 1.0.25 and now works as expected. Thanks a lot for wasting some time for helping me.
